// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAphm0u4GC49biexDvudMAag1x9XhhUr-4',
    appId: '1:555739878662:web:7e54ae37d2211228d0fa87',
    messagingSenderId: '555739878662',
    projectId: 'course-app-a30bb',
    authDomain: 'course-app-a30bb.firebaseapp.com',
    storageBucket: 'course-app-a30bb.firebasestorage.app',
    measurementId: 'G-6P3K2B7KCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA92-Cr3IkBZbO98p6Bc4I8kjtW-F3aNpM',
    appId: '1:555739878662:android:bb5113a1f9b16034d0fa87',
    messagingSenderId: '555739878662',
    projectId: 'course-app-a30bb',
    storageBucket: 'course-app-a30bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGELHs9zc_l74-_NXlPUatnUKUnuGP-PE',
    appId: '1:555739878662:ios:1d7597ab7ff61c5fd0fa87',
    messagingSenderId: '555739878662',
    projectId: 'course-app-a30bb',
    storageBucket: 'course-app-a30bb.firebasestorage.app',
    iosBundleId: 'com.example.courseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGELHs9zc_l74-_NXlPUatnUKUnuGP-PE',
    appId: '1:555739878662:ios:1d7597ab7ff61c5fd0fa87',
    messagingSenderId: '555739878662',
    projectId: 'course-app-a30bb',
    storageBucket: 'course-app-a30bb.firebasestorage.app',
    iosBundleId: 'com.example.courseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAphm0u4GC49biexDvudMAag1x9XhhUr-4',
    appId: '1:555739878662:web:85f9f59d2a6b0316d0fa87',
    messagingSenderId: '555739878662',
    projectId: 'course-app-a30bb',
    authDomain: 'course-app-a30bb.firebaseapp.com',
    storageBucket: 'course-app-a30bb.firebasestorage.app',
    measurementId: 'G-P98K486CVX',
  );
}
